// Generated by 00000233
import { observable, computed, action, makeObservable } from "mobx";
import { assertNever, newId, ObjectId, deepClone } from "ystd";
import { dataSide_server, dataSide_client, dataSide_db } from "@yuyaryshev/ydomain_common";
import {
    anyJson,
    boolean,
    Decoder,
    array,
    dict,
    object,
    oneOf,
    optional,
    string,
    number,
    union,
    intersection,
    constant,
    tuple,
} from "@mojotech/json-type-validation";

// Generated by 30000037

// Generated by 00000127
import { MetaRoot } from "@yuyaryshev/ydomain_meta";
import { FieldRef, KeyValue, KeyValueToMsgTranslator } from "@yuyaryshev/object_to_messages_ifc";
import { OdbBase, odbObject } from "@yuyaryshev/odb";
import {
    ObjectRoot,
    DomainObject,
    DomainActionSerialized,
    Domain,
    DataSide,
    isEmptyChange,
    extern_any,
    DataDirection,
} from "@yuyaryshev/ydomain_common";

import { Ysocket, UpstreamChannel } from "@yuyaryshev/ydomain_server";

// Generated by 00000128

import { SessionObject } from "./Session.js";

// Generated by 30000026
export type ClientMainDomain = Domain<ClientMainObject>;

export interface ClientMainObject {
    session: FieldRef<SessionObject | undefined>;
    globalError: FieldRef<string>;
    login: FieldRef<string>;
    pass: FieldRef<string>;
    project: FieldRef<string>;
    drawerOpen: FieldRef<boolean>;
    projectsDialog: FieldRef<boolean>;
    t: FieldRef<string>;
    a: FieldRef<string>;
}

export type ClientMainObjectKV = KeyValue<unknown, ClientMainObject>;

// Generated by 30000029
export const ClientMainDomain = {
    id: "a73e24f0-c68b-47e4-bbcb-92585e04c653",
    name: "ClientMain",
    defaultObjectRoot: undefined as ObjectRoot | undefined,

    isMyInstance: (obj: any): obj is ClientMainObject => {
        return typeof obj === "object" && obj.domain === ClientMainDomain;
    },

    // Generated by 30000021
    getOrCreate: (id: ObjectId | undefined): ClientMainObject => {
        if (!ClientMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ClientMain.getOrCreate You should first set defaultObjectRoot before using getOrCreate or else use getOrCreateEx!`,
            );
        return ClientMainDomain.getOrCreateEx(ClientMainDomain.defaultObjectRoot, id);
    },

    getOrCreateEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): ClientMainObject => {
        if (id && id.split(":")[0] !== "a73e24f0-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ClientMain.getOrCreate Incorrect domainId in id = ${id}`);
        if (!id) {
            id = "a73e24f0-c68b-47e4-bbcb-92585e04c653:" + newId();
        }
        const r = new KeyValueToMsgTranslator<unknown, ClientMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ClientMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ClientMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrThrow: (id: ObjectId): ClientMainObject => {
        if (!ClientMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ClientMain.getOrThrow You should first set defaultObjectRoot before using getOrThrow or else use getOrThrowEx!`,
            );
        return ClientMainDomain.getOrThrowEx(ClientMainDomain.defaultObjectRoot, id);
    },

    getOrThrowEx: (objectRoot: ObjectRoot, id: ObjectId): ClientMainObject => {
        if (id && id.split(":")[0] !== "a73e24f0-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ClientMain.getOrThrow Incorrect domainId in id = ${id}`);
        if (!id) {
            throw new Error(`CODE00000000 ClientMain.getOrThrow id is empty!`);
        }
        const r = new KeyValueToMsgTranslator<unknown, ClientMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ClientMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ClientMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrUndefined: (id: ObjectId | undefined): ClientMainObject | undefined => {
        if (!ClientMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ClientMain.getOrUndefined You should first set defaultObjectRoot before using getOrUndefined or else use getOrUndefinedEx!`,
            );
        return ClientMainDomain.getOrUndefinedEx(ClientMainDomain.defaultObjectRoot, id);
    },

    getOrUndefinedEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): ClientMainObject | undefined => {
        if (id && id.split(":")[0] !== "a73e24f0-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ClientMain.getOrUndefined Incorrect domainId in id = ${id}`);
        if (!id) {
            return undefined;
        }
        const r = new KeyValueToMsgTranslator<unknown, ClientMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ClientMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ClientMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000025
    verifyPermissions: (objectRoot: ObjectRoot, object: ClientMainObject, domainAction: DomainActionSerialized): boolean => {
        return true;
    },

    // Generated by 30000050
    beforeSendAction: (
        objectRoot: ObjectRoot,
        object: ClientMainObject,
        domainAction: DomainActionSerialized,
        targetDataSide: DataSide,
        destSession: SessionObject | undefined,
    ): DomainActionSerialized | undefined => {
        let cloned: true | undefined;
        let change = domainAction;
        if (targetDataSide === dataSide_db || targetDataSide === dataSide_server) return undefined;

        //-------------------------------------------- Custom code start --------------------------------------------
        if (false)
            // destSession
            return undefined;
        //-------------------------------------------- Custom code end --------------------------------------------

        return change;
    },
};
