// Generated by 00000233
import { observable, computed, action, makeObservable } from "mobx";
import { assertNever, newId, ObjectId, deepClone } from "ystd";
import { dataSide_server, dataSide_client, dataSide_db } from "@yuyaryshev/ydomain_common";
import {
    anyJson,
    boolean,
    Decoder,
    array,
    dict,
    object,
    oneOf,
    optional,
    string,
    number,
    union,
    intersection,
    constant,
    tuple,
} from "@mojotech/json-type-validation";

// Generated by 30000037

// Generated by 00000127
import { MetaRoot } from "@yuyaryshev/ydomain_meta";
import { FieldRef, KeyValue, KeyValueToMsgTranslator } from "@yuyaryshev/object_to_messages_ifc";
import { OdbBase, odbObject } from "@yuyaryshev/odb";
import {
    ObjectRoot,
    DomainObject,
    DomainActionSerialized,
    Domain,
    DataSide,
    isEmptyChange,
    extern_any,
    DataDirection,
} from "@yuyaryshev/ydomain_common";

import { Ysocket, UpstreamChannel } from "@yuyaryshev/ydomain_client";

// Generated by 00000128

import { SessionObject } from "./Session.js";

// Generated by 30000026
export type ServerMainDomain = Domain<ServerMainObject>;

export interface ServerMainObject {
    testStr: FieldRef<string>;
}

export type ServerMainObjectKV = KeyValue<unknown, ServerMainObject>;

// Generated by 30000029
export const ServerMainDomain = {
    id: "a73e24f1-c68b-47e4-bbcb-92585e04c653",
    name: "ServerMain",
    defaultObjectRoot: undefined as ObjectRoot | undefined,

    isMyInstance: (obj: any): obj is ServerMainObject => {
        return typeof obj === "object" && obj.domain === ServerMainDomain;
    },

    // Generated by 30000021
    getOrCreate: (id: ObjectId | undefined): ServerMainObject => {
        if (!ServerMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ServerMain.getOrCreate You should first set defaultObjectRoot before using getOrCreate or else use getOrCreateEx!`,
            );
        return ServerMainDomain.getOrCreateEx(ServerMainDomain.defaultObjectRoot, id);
    },

    getOrCreateEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): ServerMainObject => {
        if (id && id.split(":")[0] !== "a73e24f1-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ServerMain.getOrCreate Incorrect domainId in id = ${id}`);
        if (!id) {
            id = "a73e24f1-c68b-47e4-bbcb-92585e04c653:" + newId();
        }
        const r = new KeyValueToMsgTranslator<unknown, ServerMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ServerMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ServerMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrThrow: (id: ObjectId): ServerMainObject => {
        if (!ServerMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ServerMain.getOrThrow You should first set defaultObjectRoot before using getOrThrow or else use getOrThrowEx!`,
            );
        return ServerMainDomain.getOrThrowEx(ServerMainDomain.defaultObjectRoot, id);
    },

    getOrThrowEx: (objectRoot: ObjectRoot, id: ObjectId): ServerMainObject => {
        if (id && id.split(":")[0] !== "a73e24f1-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ServerMain.getOrThrow Incorrect domainId in id = ${id}`);
        if (!id) {
            throw new Error(`CODE00000000 ServerMain.getOrThrow id is empty!`);
        }
        const r = new KeyValueToMsgTranslator<unknown, ServerMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ServerMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ServerMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrUndefined: (id: ObjectId | undefined): ServerMainObject | undefined => {
        if (!ServerMainDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 ServerMain.getOrUndefined You should first set defaultObjectRoot before using getOrUndefined or else use getOrUndefinedEx!`,
            );
        return ServerMainDomain.getOrUndefinedEx(ServerMainDomain.defaultObjectRoot, id);
    },

    getOrUndefinedEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): ServerMainObject | undefined => {
        if (id && id.split(":")[0] !== "a73e24f1-c68b-47e4-bbcb-92585e04c653")
            throw new Error(`CODE00000000 ServerMain.getOrUndefined Incorrect domainId in id = ${id}`);
        if (!id) {
            return undefined;
        }
        const r = new KeyValueToMsgTranslator<unknown, ServerMainObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("ServerMain"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["ServerMain", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000025
    verifyPermissions: (objectRoot: ObjectRoot, object: ServerMainObject, domainAction: DomainActionSerialized): boolean => {
        return true;
    },

    // Generated by 30000050
    beforeSendAction: (
        objectRoot: ObjectRoot,
        object: ServerMainObject,
        domainAction: DomainActionSerialized,
        targetDataSide: DataSide,
        destSession: SessionObject | undefined,
    ): DomainActionSerialized | undefined => {
        let cloned: true | undefined;
        let change = domainAction;
        if (targetDataSide === dataSide_db || targetDataSide === dataSide_client) return undefined;

        //-------------------------------------------- Custom code start --------------------------------------------
        if (false)
            // destSession
            return undefined;
        //-------------------------------------------- Custom code end --------------------------------------------

        return change;
    },
};
