// Generated by 00000233
import { observable, computed, action, makeObservable } from "mobx";
import { assertNever, newId, ObjectId, deepClone } from "ystd";
import { dataSide_server, dataSide_client, dataSide_db } from "@yuyaryshev/ydomain_common";
import {
    anyJson,
    boolean,
    Decoder,
    array,
    dict,
    object,
    oneOf,
    optional,
    string,
    number,
    union,
    intersection,
    constant,
    tuple,
} from "@mojotech/json-type-validation";

// Generated by 30000037
import { UserObject } from "./User.js";

// Generated by 00000127
import { MetaRoot } from "@yuyaryshev/ydomain_meta";
import { FieldRef, KeyValue, KeyValueToMsgTranslator } from "@yuyaryshev/object_to_messages_ifc";
import { OdbBase, odbObject } from "@yuyaryshev/odb";
import {
    ObjectRoot,
    DomainObject,
    DomainActionSerialized,
    Domain,
    DataSide,
    isEmptyChange,
    extern_any,
    DataDirection,
} from "@yuyaryshev/ydomain_common";

import { Ysocket, UpstreamChannel } from "@yuyaryshev/ydomain_client";

// Generated by 00000128

import { SessionObject } from "./Session.js";

// Generated by 30000026
export type WorkspaceDomain = Domain<WorkspaceObject>;

export interface WorkspaceObject {
    name: FieldRef<string>;
    user: FieldRef<UserObject | undefined>;
}

export type WorkspaceObjectKV = KeyValue<unknown, WorkspaceObject>;

// Generated by 30000029
export const WorkspaceDomain = {
    id: "08ea9172-85d6-43f0-9309-3a49aeab0d24",
    name: "Workspace",
    defaultObjectRoot: undefined as ObjectRoot | undefined,

    isMyInstance: (obj: any): obj is WorkspaceObject => {
        return typeof obj === "object" && obj.domain === WorkspaceDomain;
    },

    // Generated by 30000021
    getOrCreate: (id: ObjectId | undefined): WorkspaceObject => {
        if (!WorkspaceDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 Workspace.getOrCreate You should first set defaultObjectRoot before using getOrCreate or else use getOrCreateEx!`,
            );
        return WorkspaceDomain.getOrCreateEx(WorkspaceDomain.defaultObjectRoot, id);
    },

    getOrCreateEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): WorkspaceObject => {
        if (id && id.split(":")[0] !== "08ea9172-85d6-43f0-9309-3a49aeab0d24")
            throw new Error(`CODE00000000 Workspace.getOrCreate Incorrect domainId in id = ${id}`);
        if (!id) {
            id = "08ea9172-85d6-43f0-9309-3a49aeab0d24:" + newId();
        }
        const r = new KeyValueToMsgTranslator<unknown, WorkspaceObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("Workspace"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["Workspace", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrThrow: (id: ObjectId): WorkspaceObject => {
        if (!WorkspaceDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 Workspace.getOrThrow You should first set defaultObjectRoot before using getOrThrow or else use getOrThrowEx!`,
            );
        return WorkspaceDomain.getOrThrowEx(WorkspaceDomain.defaultObjectRoot, id);
    },

    getOrThrowEx: (objectRoot: ObjectRoot, id: ObjectId): WorkspaceObject => {
        if (id && id.split(":")[0] !== "08ea9172-85d6-43f0-9309-3a49aeab0d24")
            throw new Error(`CODE00000000 Workspace.getOrThrow Incorrect domainId in id = ${id}`);
        if (!id) {
            throw new Error(`CODE00000000 Workspace.getOrThrow id is empty!`);
        }
        const r = new KeyValueToMsgTranslator<unknown, WorkspaceObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("Workspace"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["Workspace", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000021
    getOrUndefined: (id: ObjectId | undefined): WorkspaceObject | undefined => {
        if (!WorkspaceDomain.defaultObjectRoot)
            throw new Error(
                `CODE00000000 Workspace.getOrUndefined You should first set defaultObjectRoot before using getOrUndefined or else use getOrUndefinedEx!`,
            );
        return WorkspaceDomain.getOrUndefinedEx(WorkspaceDomain.defaultObjectRoot, id);
    },

    getOrUndefinedEx: (objectRoot: ObjectRoot, id: ObjectId | undefined): WorkspaceObject | undefined => {
        if (id && id.split(":")[0] !== "08ea9172-85d6-43f0-9309-3a49aeab0d24")
            throw new Error(`CODE00000000 Workspace.getOrUndefined Incorrect domainId in id = ${id}`);
        if (!id) {
            return undefined;
        }
        const r = new KeyValueToMsgTranslator<unknown, WorkspaceObject>({
            baseTypeMeta: objectRoot.odbConnection.odbBase.__metaRoot.expectType("Workspace"),
            stateReader: objectRoot.odbConnection,
            actionProcessor: objectRoot.stdActionProcessor,
            path: ["Workspace", id],
            createIfNotExists: true,
        });
        return r.asObj();
    },

    // Generated by 30000025
    verifyPermissions: (objectRoot: ObjectRoot, object: WorkspaceObject, domainAction: DomainActionSerialized): boolean => {
        return true;
    },

    // Generated by 30000050
    beforeSendAction: (
        objectRoot: ObjectRoot,
        object: WorkspaceObject,
        domainAction: DomainActionSerialized,
        targetDataSide: DataSide,
        destSession: SessionObject | undefined,
    ): DomainActionSerialized | undefined => {
        let cloned: true | undefined;
        let change = domainAction;

        //-------------------------------------------- Custom code start --------------------------------------------
        if (false) return undefined;
        //-------------------------------------------- Custom code end --------------------------------------------

        return change;
    },
};
